"""add_call_metrics_table

Revision ID: b88491b78a30
Revises: f81484ed308c
Create Date: 2025-11-20 23:29:57.631686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88491b78a30'
down_revision: Union[str, Sequence[str], None] = 'f81484ed308c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('call_initiated_at', sa.DateTime(), nullable=True),
    sa.Column('websocket_connected_at', sa.DateTime(), nullable=True),
    sa.Column('call_answered_at', sa.DateTime(), nullable=True),
    sa.Column('streaming_started_at', sa.DateTime(), nullable=True),
    sa.Column('first_audio_frame_at', sa.DateTime(), nullable=True),
    sa.Column('time_to_websocket_ms', sa.Integer(), nullable=True),
    sa.Column('time_to_answer_ms', sa.Integer(), nullable=True),
    sa.Column('time_to_streaming_ms', sa.Integer(), nullable=True),
    sa.Column('time_to_first_audio_ms', sa.Integer(), nullable=True),
    sa.Column('total_audio_frames_sent', sa.Integer(), nullable=True),
    sa.Column('total_audio_frames_received', sa.Integer(), nullable=True),
    sa.Column('total_audio_frames_dropped', sa.Integer(), nullable=True),
    sa.Column('audio_drop_rate_percent', sa.Float(), nullable=True),
    sa.Column('max_audio_queue_depth', sa.Integer(), nullable=True),
    sa.Column('avg_audio_queue_depth', sa.Float(), nullable=True),
    sa.Column('vad_config', sa.JSON(), nullable=True),
    sa.Column('vad_trigger_count', sa.Integer(), nullable=True),
    sa.Column('speech_start_count', sa.Integer(), nullable=True),
    sa.Column('speech_end_count', sa.Integer(), nullable=True),
    sa.Column('interruption_count', sa.Integer(), nullable=True),
    sa.Column('time_to_first_ai_response_ms', sa.Integer(), nullable=True),
    sa.Column('avg_ai_response_time_ms', sa.Float(), nullable=True),
    sa.Column('ai_turn_count', sa.Integer(), nullable=True),
    sa.Column('user_turn_count', sa.Integer(), nullable=True),
    sa.Column('websocket_duration_ms', sa.Integer(), nullable=True),
    sa.Column('websocket_reconnect_count', sa.Integer(), nullable=True),
    sa.Column('network_error_count', sa.Integer(), nullable=True),
    sa.Column('gemini_session_duration_ms', sa.Integer(), nullable=True),
    sa.Column('gemini_connection_errors', sa.Integer(), nullable=True),
    sa.Column('gemini_model_version', sa.String(), nullable=True),
    sa.Column('call_completion_status', sa.String(), nullable=True),
    sa.Column('disconnection_reason', sa.String(), nullable=True),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('twilio_call_sid', sa.String(), nullable=True),
    sa.Column('twilio_stream_sid', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_metrics_call_id'), 'call_metrics', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_metrics_workflow_id'), 'call_metrics', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_metrics_workflow_id'), table_name='call_metrics')
    op.drop_index(op.f('ix_call_metrics_call_id'), table_name='call_metrics')
    op.drop_table('call_metrics')
    # ### end Alembic commands ###
